let table = document.createElement('table');
let tr1 = document.createElement('tr');
table.appendChild(tr1);
let trd1 = document.createElement('td');
trd1.textContent = 'Name';
tr1.appendChild(trd1);
let trd2 = document.createElement('td');
trd2.textContent = 'Age';
tr1.appendChild(trd2);

let tr2 = document.createElement('tr');
table.appendChild(tr2);
let tr2d1 = document.createElement('td');
tr2d1.textContent = 'revo';
tr2.appendChild(tr2d1);
let tr2d2 = document.createElement('td');
tr2d2.textContent = 20;
tr2.appendChild(tr2d2);

let tr3 = document.createElement('tr');
table.appendChild(tr3);
let tr3d1 = document.createElement('td');
tr3d1.textContent = 'Ram';
tr3.appendChild(tr3d1);
let tr3d2 = document.createElement('td');
tr3d2.textContent = 21;
tr3.appendChild(tr3d2);

let tr4 = document.createElement('tr');
table.appendChild(tr4);
let tr4d1 = document.createElement('td');
tr4d1.textContent = 'sundhar';
tr4.appendChild(tr4d1);
let tr4d2 = document.createElement('td');
tr4d2.textContent = 22;
tr4.appendChild(tr4d2);

table.style.border = '1px solid black';
trd1.style.border = '1px solid black';
trd2.style.border = '1px solid black';
tr2d1.style.border = '1px solid black';
tr2d2.style.border = '1px solid black';
tr3d1.style.border = '1px solid black';
tr3d2.style.border = '1px solid black';
tr4d1.style.border = '1px solid black';
tr4d2.style.border = '1px solid black';


console.log(table);
document.body.appendChild(table);

let ul1 = document.createElement('ul');
let li1 = document.createElement('li');
let li2 = document.createElement('li');
let li3 = document.createElement('li');
let li4 = document.createElement('li');
li1.textContent = 'css';
li2.textContent = 'html';
li3.textContent = 'java';
li4.textContent = 'js';
document.body.appendChild(ul1);
ul1.appendChild(li1);
ul1.appendChild(li2);
ul1.appendChild(li3);
ul1.appendChild(li4);
let p1 = document.createElement('p');
console.log('===========================');
p1.textContent = 'this is unordered list';
document.body.appendChild(p1);
let ol1 = document.createElement('ol');
let li5 = document.createElement('li');
let li6 = document.createElement('li');
let li7 = document.createElement('li');
let li8 = document.createElement('li');
li5.textContent = 'css';
li6.textContent = 'html';
li7.textContent = 'java';
li8.textContent = 'js';
document.body.appendChild(ol1);
ol1.appendChild(li5);
ol1.appendChild(li6);
ol1.appendChild(li7);
ol1.appendChild(li8);
let header1 = document.createElement('h1');
header1.textContent = 'this is ordered list';
document.body.appendChild(header1);
